# Generated by Django 4.2.6 on 2023-10-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
