# Generated by Django 4.2.6 on 2023-10-25 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_apps', '0003_remove_todomodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
