name: ruff-format

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
      - run: pip install ruff
      - run: ruff format --check --config pyproject.toml --diff .
