# Generated by Django 4.2.6 on 2023-10-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todomodel_created_at_todomodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='updated_at',
        ),
    ]
