# Generated by Django 4.2.6 on 2023-10-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_alter_jobdescription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='company',
            field=models.ForeignKey(db_comment='해당 채용공고를 등록한 회사입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='employment.company'),
        ),
    ]
