# Generated by Django 4.2.6 on 2023-10-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정일"),
                ),
                (
                    "company_name",
                    models.CharField(help_text="회사이름", max_length=50),
                ),
                ("country", models.CharField(help_text="국가", max_length=50)),
                ("city", models.CharField(help_text="도시", max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정일"),
                ),
                ("position", models.CharField(help_text="직무", max_length=50)),
                ("content", models.TextField(help_text="채용내용")),
                ("reward", models.PositiveIntegerField(help_text="채용보상금")),
                (
                    "skill",
                    models.CharField(help_text="여러 기술", max_length=200),
                ),
                ("start_date", models.DateField(help_text="채용시작일")),
                ("end_date", models.DateField(help_text="채용마감일")),
                (
                    "company",
                    models.ForeignKey(
                        db_comment="해당 채용공고를 등록한 회사입니다.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_description",
                        to="job_description.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정일"),
                ),
                (
                    "job_description",
                    models.ForeignKey(
                        db_comment="해당 지원이력을 가지고 있는 채용공고입니다.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_description.jobdescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정일"),
                ),
                ("name", models.CharField(help_text="이름", max_length=50)),
                ("age", models.PositiveIntegerField(help_text="나이")),
                (
                    "job_description",
                    models.ManyToManyField(
                        related_name="users",
                        through="job_description.ResumeHistory",
                        to="job_description.jobdescription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="resumehistory",
            name="user",
            field=models.ForeignKey(
                db_comment="해당 지원이력을 가지고 있는 유저 입니다.",
                on_delete=django.db.models.deletion.CASCADE,
                to="job_description.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="resumehistory",
            constraint=models.UniqueConstraint(
                fields=("job_description", "user"),
                name="unique_in_application",
            ),
        ),
    ]
