# Generated by Django 4.2.6 on 2023-11-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_description', '0002_rename_job_description_user_job_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='company',
            field=models.ForeignKey(db_comment='해당 채용공고를 등록한 회사입니다.', on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to='job_description.company'),
        ),
    ]
